apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.appName }}
spec:
  provider:
    vault:
      server: "http://vault-internal.azdevopsv82.online:8200"
      path: "roboshop-{{ .Values.env }}"
      version: "v1"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
